### ISSUE TITLE
Decide whether to simplify FHIR Parameters

### ISSUE THREAD

**Issue by jmandel** [cds-hooks/cds-hooks#11]
I.e. Should we serialize in a simpler way by flattening:

``` json
{
  "name": "a",
  "value": "b"
}
```

to:

``` json
{
  "a": "b"
}

?
```

**Comment by dmccallie** [comment]
Non-developer's comment:  Yes, go with the simpler version.

**Comment by jmandel** [comment]
At that level, yes (and it would be an easy decision). The issue is if we do "simplify", parsing payloads with standard FHIR libraries gets harder (i.e. Impossible). To spell this out:

##### 1. Example "Parameters" with a prescription in-context:

``` json
{
   "resourceType":"Parameter",
   "parameter":[
      {
          "name": "patient",
          "valueId": "1288992"
      },
      {
         "name":"context",
         "resource":{
            "resourceType":"MedicationOrder",
            "dateWritten":"2016-03-17",
            "dateEnded":"2016-04-17",
            "status":"draft",
            "patient":{
               "reference":"Patient/1288992"
            },
            "medicationCodeableConcept":{
               "text":"24 HR metoprolol succinate 25 MG Extended Release Oral Tablet [Toprol]",
               "coding":[
                  {
                     "display":"24 HR metoprolol succinate 25 MG Extended Release Oral Tablet [Toprol]",
                     "system":"http://www.nlm.nih.gov/research/umls/rxnorm",
                     "code":"866429"
                  }
               ]
            }
         }
      }
   ]
}
```

##### 2. "Simplified" version of above:

``` json
{
   "patient":"1288992",
   "context":{
      "resourceType":"MedicationOrder",
      "dateWritten":"2016-03-17",
      "dateEnded":"2016-04-17",
      "status":"draft",
      "patient":{
         "reference":"Patient/1288992"
      },
      "medicationCodeableConcept":{
         "text":"24 HR metoprolol succinate 25 MG Extended Release Oral Tablet [Toprol]",
         "coding":[
            {
               "display":"24 HR metoprolol succinate 25 MG Extended Release Oral Tablet [Toprol]",
               "system":"http://www.nlm.nih.gov/research/umls/rxnorm",
               "code":"866429"
            }
         ]
      }
   }
}
```

You'll note that as the payloads get large, and contain more wholesale FHIR resources inside, the difference that "simplified" makes decreases. And then there's a real cost to the simplified version.

Let's say I'm programming in a language where I use a FHIR client library (java, python, c#, swift, ...) With the standard "Parameters", resource, I can say:

``` java
MedicationOrder o = incomingData
  .getParameter()
  .filter(p -> p.getName().eqauls("context")
  .get(0)
  .getResource()

// now `o` is a nice, typed FHIR object
// we can do things like
o. getDateWritten()
```

But in the "simplified" version, the standard FHIR library doesn't parse the Parameters. So you also don't get visibility into the resources inside (like `MedicationOrder`, in this case).

**Comment by dmccallie** [comment]
I'm not sure I quite understand the difference. Can't the parser introspect to find the value of "patient", since it would presumably know that "patient" was one of the parameters to be passed in?  In your example, there would be a library object for a "parameter" resource, but you'd still have to know that the parameter resource includes "patient" in order to use it?  How is that different from just asked the top level object for "patient?"  Or are there a fixed and pre-standardized set of parameter types in the Parameter Resource?  If the latter, how do you introduce new parameters?

Oh, I get it - you'd have to ask the Parameter resource: "what's the next parameter's name?" and then "what's the next parameter's value" -- but your code will still have to know that you needed to find a "patient" parameter, so why not just ask for "patient" directly via introspection?

I'm probably missing something.

**Comment by jmandel** [comment]
I think what you're missing is that I'm not describing what parsers _could_
do -- I'm talking about what existing FHIR parsers actually do today, in 5+
languages. That's behavior lots of developers use today, and it would be
nice to get "for free" in CDS Hooks. And that's what we'd give up by
inventing a new "simpler" format. (Otherwise, if I'm using no libraries,
the simple formats is better. The advantage of the Parameters resource is a
pure ecosystem effect.)

**Comment by dmccallie** [comment]
OK, so I am not sure why you asked the question? If it's free, why even consider a change?

**Comment by jmandel** [comment]
The simplification is something @kpshek proposed on our Google Group, and I've been thinking hard about it. I wanted to capture the reasoning as a discrete issue, and here it is. And your comment forced me to be explicit about where I see the value of status quo.
