### ISSUE TITLE
Determine an approach to security

### ISSUE THREAD

**Issue by jmandel** [cds-hooks/cds-hooks#12]
Two main use cases for authentication / authorization
1. CDS Service needs to authenticate the EHR for a service invocation
2. EHR needs to authenticate the service --> simple bearer tokens

For (1), we could use a signed JWT in a header. Or an OAuth flow.

For (2) we have a current solution (passing OAuth tokens in the input parameters to `$cds-hook`). Is this good enough?

**Comment by kpshek** [comment]
This issue was moved to cds-hooks/docs#7
