### ISSUE TITLE
Rename activities to hooks

### ISSUE THREAD

**Issue by kpshek** [cds-hooks/cds-hooks#13]
Currently, CDS Hooks uses the term `activity` for thinks like `patient-view` and `medication-prescribe` to describe EHR activities that result in a CDS Service invocation. In the current documentation, the term `hook` is sometimes used as well to describe `activity`. For example:

> Each CDS service can return any number of cards in response to the hook
> ...
> At that point, the EHR re-triggers the initial CDS hook
> ...
> The CDS Service registers a set of "hooks" with the EHR indicating

Given that this project is named CDS **Hooks** and that we're already using the terms `activity` and `hook` synonymously, I propose that we just use the term `hook`.

Which ever way we decide, I'll submit a PR to clarify the documentation so that it is consistent (which is why I've assigned this issue to myself).

**Comment by jmandel** [comment]
This is a great point: what precisely is the "hook" in CDS Hooks? 

The way I've tried to describe it, the user engages in a series of "activities" in the EHR, and some of these activities trigger an event emitter (a "hook") that broadcasts details of the activity to external services.

I think it feels just fine to have a "hook catalog", for example, and to have `hookInstance` and `hook` fields in our payloads.

When we talk about what the user is doing to actually trigger this stuff, I think the word "activity" is useful, but that word doesn't need to appear in our structured data artifacts. Does that make sense?

**Comment by kpshek** [comment]
Cool, that makes sense to me. I'll have a PR late tonight with proposed changes!

**Comment by kpshek** [comment]
From #10:

> In the case where a single $cds-hook endpoint serves multiple different activities (medication-prescribe and patient-view, for example -- btw, see how using the word "hooks" there would have been akward?), I see the value in having a list of hooks.

I would have worded that something like:

> In the case where a single $cds-hook endpoint offers multiple services across several hooks...

**Comment by jmandel** [comment]
Mmm. Maybe the operation shouldn't be called `cds-hook` though. I mean, is the "hook" something the EHR does, or something the CDS Service exposes, or both? Both feels unsatisfying here, like we need more/better/clearer terms.

**Comment by kpshek** [comment]
I agree. It doesn't feel completely right. I'll mull over this more tonight...

**Comment by kpshek** [comment]
What about this?

> EHRs offer **hooks** for areas or activities within the EHR in which a CDS Service can _hook_ into.
> 
> CDS Providers offers **services** which are invoked by the EHR at the desired hook.

So,
- CDS Providers, not CDS Services. This is because it's awkward to say "CDS Services offers services..."
- Hooks, not activities (see above). Activities imply user action and certainly today our hooks are invoked as a result of explicit user action. However, I'm certain we'll see hooks in the future which are purely passive (eg, the EHR offers a hook into an _area_ of the application that is always visible; like a notification bar / system tray)

This terminology would have the following ramifications:
- POST /$cds-service for invoking a service in the CDS Provider
- GET /$cds-service-metadata to get the metadata for all services offered by the CDS Provider

Thoughts @jmandel?

**Comment by jmandel** [comment]
I find this very clear, and I like the notion that hooks are exposed by the EHR, and services are exposed by the CDS Provider. That solves a naming problem that's been bugging me for a while. 

Slight tweaks to the overview (see if you are okay with "workflow" in this sense - I do agree with your point about  areas of the screen, but it's hard to express concisely):

> EHRs offer "hooks" into specific points in the workflow where external CDS Providers can be consulted 
> 
> CDS Providers offer "services" that respond to an EHR's hooks

(I'm still on the fence about "trigger".)

**Comment by kpshek** [comment]
I'm fine with your changes @jmandel and like using _workflow_ as this describes the intended integration much better!

**Comment by kpshek** [comment]
Closing out this obsolete issue. See http://cds-hooks.org and [cds-hooks/docs](https://github.com/cds-hooks/docs) for the latest.
