### ISSUE TITLE
define an approach to "trigger guards"

### ISSUE THREAD

**Issue by jmandel** [cds-hooks/cds-hooks#17]
Providing "trigger guards" for CDS Service Invocation: We’ve encountered several CDS services that are only relevant for a particular set of patients. For instance, a bilirubin CDS service would only be of interest to newborns, so it would be optimal if the EHR would only call the service for that subset of qualifying patients. It would be great to have a discussion around this topic and see if we can at least define conventions for how this is documented in CDS services.

**Comment by dmccallie** [comment]
I think we should be cautious to avoid over-engineering the notion of
"trigger guards." Even if you could specify some "executable" logic as a
trigger guard, there would likely be lots of local detail (setting of care,
provider specialty, provider's preferences, etc) that could not be captured
in the external service's trigger guard logic statements. This could lead
to a messy mix of local rules engine trying to interplay with the external
logic defined by a different rules model.

It makes sense to define some recommendations about how to _document_ the
external service's specification. For example, the external definitions
could be encouraged to use FHIR Profile value sets to define their logic
(e.g.,use the profile's valuesets to minimize the chance of data mismatch.)

--david

**Comment by jmandel** [comment]
Thanks for weighing in! I think I agree in principle -- but I'll also say that one of the best ways to _document_ an expectation unambiguously can be to use a well-defined grammar. In other words, I wouldn't necessarily be against using something notionally executable as a documentation format.

**Comment by dmccallie** [comment]
As long as "notationally executable" is readable by humans (in other words,
not an XML-encoded AST)...

**Comment by kpshek** [comment]
> in other words, not an XML-encoded AST

Well, there goes 2 days worth of work... 😜

**Comment by kpshek** [comment]
This issue was moved to cds-hooks/docs#6
