### ISSUE TITLE
API definition: `context` as bundle instead of array

### ISSUE THREAD

**Issue by tmarthal** [cds-hooks/cds-hooks#18]
In the request API definition, the context is given as an array:
`"context" : [],`

Here is the yaml definition (https://github.com/cds-hooks/api/blob/master/cds-hooks.yaml#L119): 

``` context:
        type: array
        items:
          type: object
```

However, in the Hook Catalog area of the cds-hooks api, the context examples are shown as an object. Is this object a FHIR bundle (with one or more FHIR resources within it) and not an array?

For example, in the Hook Catalog `medication-prescribe` section, there is a MedicationResource:

```
"context": {
    "resourceType": "MedicationPrescription",
    "medicationCodeableConcept": {
      "...": "<snipped for brevity>"
    }
  }
```

The example, to submit multiple prescriptions, would need to be a FHIR resource with the multiple medications: 

```
{
    "resourceType": "Bundle",
    "entry": [{
        "resource": {
            "resourceType": "Medication",
            "id": "1146434", <snip>
        }
    }, {
        "resource": {
            "resourceType": "Medication",
            "id": "731535", <snip>
        }
    }]
}
```

I can submit a PR with the updated yml definition, but I wanted to verify that the `context` variable is a FHIR resource and not an array.

**Comment by jmandel** [comment]
Our notion was that the definition of the `context` property would be hook-specific. So for the prescribe hook, the context is a single resource; for other hooks, it may differ. I'd prefer not to say "it's always a bundle" before we have defined additional hooks (with context) that actually flesh out the requirements here — but _I do think it's definitely a mistake to use an array in our swagger defs_, since our examples and reference implementation use bare objects to convey data (e.g. we have examples like:

```
  "context": {
    "resourceType": "MedicationPrescription",
    "medicationCodeableConcept": {
      "...": "<snipped for brevity>"
    }
  }
```

```
{
  "context": {
    "resourceType": "MedicationPrescription",
    "medicationCodeableConcept": {
      "...": "<snipped for brevity>"
    }
  }
}
```

**Comment by robs16** [comment]
Has there been any further thought on this? The examples also show some significant inconsistency in this respect as they show a single resource per the example above yet the related documentation states:

>Contextual data: The **set** of proposed medication prescriptions. using the FHIR medicationPrescription resource. See example in the sidebar.

**Comment by kpshek** [comment]
Closing obsolete issue. Please log any subsequent issues to [cds-hooks/docs](https://github.com/cds-hooks/docs)
