### ISSUE TITLE
The source.logo doesn't display on the card

### ISSUE THREAD

**Issue by travistcummings** [cds-hooks/cds-hooks#19]
The following card should display an icon that is the source.image.  But I don't see the icon on the card displayed.

{
  "summary": "Example Card",
  "indicator": "info",
  "detail": "Add an XYZ complimentary medication OR switch patient order to ABC. See SMART app for more details.",
  "source": {
    "label": "Medicine Library",
    "url": "https://example.com",
    "icon": "https://content.hspconsortium.org/images/my-web-app/logo/lightbulb_100x100.png"
  },
  "links": [
    {
      "label": "Medication SMART app",
      "url": "https://example.com/launch",
      "type": "smart"
    }
  ]
}

**Comment by kpshek** [comment]
@travistcummings - Can you log this to [cds-hooks/sandbox](https://github.com/cds-hooks/sandbox) please?
