### ISSUE TITLE
Write a CDS Service developer's tutorial

### ISSUE THREAD

**Issue by jmandel** [cds-hooks/cds-hooks#2]
If you've successfully exposed a CDS Service, write up your experience as a developer tutorial. Explain the toolset you used, and describe the integration process in a set-by-step fashion.

Bonus points if you can provide an easy way for developers to "follow along at home"!

**Comment by mattberther** [comment]
I did a few of these services over the past couple days and was planning on doing a blog post on this. Ill provide that back to the group and we can add to cds-hooks.org.

**Comment by kpshek** [comment]
This issue was moved to cds-hooks/docs#9
