### ISSUE TITLE
Stand up a "test card service" to host "test cards"

### ISSUE THREAD

**Issue by jmandel** [cds-hooks/cds-hooks#5]
Depends on #4.
- Simple nodejs web server that "acts like" a set of CSD Services, each of which responds with fixturized data from #4.
- Deployable via docker
- Deploy to `https://test-service.cds-hooks.org`

**Comment by mattberther** [comment]
@jmandel take a look at https://github.com/cds-hooks/cds-card-service. I also started the fixtures repository referenced in #4 in that project by seeding it with the Healthwise cards we created during the Connectathon.

**Comment by jmandel** [comment]
Fabulous -- and I know that @kpshek has created some fixture cards too. (Kevin, can you point us to them?)

Will you add a discovery endpoint (I guess it could just advertise a single service, or maybe two is better, just on the principle of covering more of the caller API surface area)

**Comment by mattberther** [comment]
Will do. Just taking off now and will have some time on the plane.

**Comment by kpshek** [comment]
This is fantastic @mattberther, thanks!

I moved over my CDS Service example Rails app to the cds-hooks org: [cds-hooks/cds-service-example](https://github.com/cds-hooks/cds-service-example).

I think having as many CDS Service examples across a variety of languages and platforms is both beneficial to helping attract a diverse set of developers and ensuring the CDS Hooks API is broadly implementable. To this end, I'd love to see a consistent naming strategy for these CDS Service example repositories. My proposal is cds-service-example-_[language|platform]_

So, right now we have:
- cds-service-example-node
- cds-service-example-rails

I imagine we'll quickly have:
- cds-service-example-sinatra
- cds-service-example-java
- cds-service-example-django
- etc

I'm open to other names other than cds-service-example (maybe cds-service-demo?)

When we start writing our developer tutorial (#2), we can then reference these example projects for each language/platform and now developers have a concrete example for their particular technology skill set.

Thoughts?

**Comment by mattberther** [comment]
@jmandel https://github.com/cds-hooks/cds-card-service/commit/937ee723ec2108cfb5f095f282f395686c30fccc should implement the test card server using the v2 api.

@kpshek I like it. I can rename the node repo. Do you want to rename yours to include -rails? Ill have some time on a plane in a bit, so I can create a python and c# implementation.

**Comment by kpshek** [comment]
@mattberther - Done! - [cds-service-example-rails](https://github.com/cds-hooks/cds-service-example-rails)

I'm going to knock out a [Sinatra](http://www.sinatrarb.com/) implementation too. That will give me a chance to refactor out the Ruby models into a separate gem that both the Rails & Sinatra implementations leverage.

**Comment by mattberther** [comment]
Done too. - [cds-service-example-nodejs](https://github.com/cds-hooks/cds-service-example-nodejs)

Also just pushed [cds-service-example-csharp](https://github.com/cds-hooks/cds-service-example-csharp)

**Comment by jmandel** [comment]
Great! Deployed to https://test-service.cds-hooks.org via https://github.com/cds-hooks/docker-stack

**Comment by mattberther** [comment]
Thanks @jmandel. Anything remaining on this issue?

**Comment by jmandel** [comment]
No, that does it!
