### ISSUE TITLE
Build a "CDS invoker" that simulates an EHR

### ISSUE THREAD

**Issue by jmandel** [cds-hooks/cds-hooks#6]
Nodejs-based web service that simulates the EHR's side of a CDS Hooks interaction, for testing purposes. To start, the service exposes one API call, `invoke`, that causes it to call an external CDS Service and pass through the resulting cards. (Later, we'll build in card validation so this can be the basois of an automated testing tool.)

```
POST /invoke
{
  "service": "http://services.example.com/$cds-hook",
  "payload": {
    // data to call with
  }
}
--> cards, timing information
```
- deployable via Docker
- deployed to `https://invoker.cds-hooks.org`

**Comment by mattberther** [comment]
@jmandel FYI.

Ive resolved this issue (except for the deployment) and #8 in https://github.com/cds-hooks/cds-invoker

**Comment by jmandel** [comment]
Great! Deployed to https://invoker.cds-hooks.org via https://github.com/cds-hooks/docker-stack

**Comment by mattberther** [comment]
Outstanding. Thanks @jmandel.
