### ISSUE TITLE
Build a "card validator" to evaluate CDS payloads

### ISSUE THREAD

**Issue by jmandel** [cds-hooks/cds-hooks#7]
This should be a JavaScript library that takes, as input, a string representing the response from a CDS service. It should return a promise that will either `resolve` to a JSON object (the payload, parsed) or `reject` to an array of errors indicating what was wrong. 
- available via as an NPM module
- also compiled with weback to UMD

**Comment by mattberther** [comment]
@jmandel i had a little free time this afternoon and put this together. let me know if this is what you had in mind.

https://github.com/mattberther/cds-validator

**Comment by jmandel** [comment]
Awesome -- thanks very much for this! Some quick questions:
1. Did you re-write the schema by hand, or did you manage to re-use bits from our Swagger definitions? Maybe we should publish those via npm (as JSON) to make this kind of thing easier.
2. Would you be willing to move the repo into the cds-hooks org and own it there? (Otherwise we're happy to fork it.)

**Comment by mattberther** [comment]
Yeah. I made it by hand, but referenced the http://cds-hooks.github.io/docs/#cds-service-response page.

Happy to move it to the cds-hooks org.

**EDIT** I apparently need permissions to cds-hooks to move it. :)

**Comment by jmandel** [comment]
Beautiful -- thanks!!

**Comment by kpshek** [comment]
Thanks @mattberther!
