### ISSUE TITLE
Integrate "card validator" into "CDS Invoker"

### ISSUE THREAD

**Issue by jmandel** [cds-hooks/cds-hooks#8]
Incorporate the library (#7) into the CDS Invoker (#6). Now, the CDS Invoker responds to invalid payloads with a `502` error, with a JSON body as provided by the CDS Invoker.
- Re-deploy to `https://invoker.cds-hooks.org`

**Comment by mattberther** [comment]
Resolved by https://github.com/cds-hooks/cds-invoker/commit/b437e11ca3a6ea8be1b69f8de06503418f70aa55

**Comment by jmandel** [comment]
Beautiful! I'll work on getting this stuff deployed as indicated.

**Comment by mattberther** [comment]
@jmandel thanks for the deploy. I think we can close this one too.
