### ISSUE TITLE
Decide expectations for preFetch behavior

### ISSUE THREAD

**Issue by jmandel** [cds-hooks/cds-hooks#9]
Is this optional for EHRs? Can an EHR provide pre-fetch data for some queries but not others? Does an app need to fallback to REST queries when pre-fetch data are missing?

**Comment by dmccallie** [comment]
I think pre-fetch should be optional, and should be based on best effort rather than a formal query definition.  Partial pre-fetch should be allowed also.  For example, perhaps Patient and Encounter resources are readily available to the EHR's triggering mechanism.  Those could be shared via pre-fetch, even if other data is not readily available (and must be queried with app-triggered FHIR calls.)

**Comment by jmandel** [comment]
"Partial" is a slight issue, in that we'd need a way for the EHR to explicitly indicate which requests it was attempting to fulfill, and which ones it was skipping. As currently specified, the only way a client can tell which preFetch "asks" have been fulfilled is by iterating over the in-order list of responses, and correlating them one by one with requests.

#### Example

CDS Service has pre-fetch request of:

``` json
preFetch: [
  "Patient/{{Patient.id}}",
  "MedicationOrder?patient={{Patient.id}}"
]
```

EHR supplies it with data like:

``` json
[{
  "name": "preFetchData",
  "resource": {
      "resourceType": "Bundle",
      "entry: [
        // two resources in bundle:
        {}, // response to GET Patient (a Patient resource)
        {} // response to GET MedicationOrder (a Bundle of MedicationOrders)
      ]
    }
}]
```

Now the client looks at the order of entries, and matches them up one-by-one with its requests. If we can allowed the EHR to simply skip some preFetch entries, it would need to include some kind of placeholder in the response. Otherwise the client would be able to tell _which_ thing was missing without deep inspection and guesswork.

But if we made that rule, I'd be okay with partial responses.

Anyway, I'm resigned to the notion that apps will need to detect missing data and fall back to FHIR API requests to fill the gaps. I think we can automate that logic with a (totally optional and totally generic) proxy (see #3) for developers who prefer to avoid this pain.

**Comment by kpshek** [comment]
Closing this issue in favor of issue cds-hooks/docs#5
